### PR TITLE
Tatar Translation!

### PR DESCRIPTION
**Pull request by Amirhan-Taipovjan-Greatest-I**
Vanilla-ish Tatar Translation!

### CODE REVIEW

**Comment by QboiDev** [comment]
Translations can also be done at: https://crowdin.com/project/ultreon-team
*As mentioned in the README*

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> Translations can also be done at: https://crowdin.com/project/ultreon-team

Uh... I didn't see that... My bad.

**Comment by QboiDev** [comment]
Well, the language you added wasn't actually added on Crowdin, so this is ok anyways

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> Well, the language you added wasn't actually added on Crowdin, so this is ok anyways

Thank You!

**Comment by QboiDev** [comment]
Merged!

**Pull request merged**
